package main

import (
	"context"
	"fmt"

	"github.com/nakamurakzz/generate-go-sruct/config/server"
	"github.com/nakamurakzz/generate-go-sruct/presentation/response"
)

func main() {
	ctx := context.TODO()

	// Load config from file
	// LoadFromPath function is generated by pkl-go. This function loads the static value from the pkl file.
	cnf, err := server.LoadFromPath(ctx, "pkl/AppConfig.pkl")
	if err != nil {
		fmt.Println(err)
		return
	}

	fmt.Printf("Host: %s, Port: %d\n", cnf.Host, cnf.Port)

	// Create response struct
	// Newxxx function is generated manually
	person := response.NewPerson(1, "person name")
	group := response.NewGroup("group name")

	fmt.Printf("Id: %d, Name: %s\n", person.Id, person.Name)
	fmt.Printf("GroupName: %s\n", group.GroupName)
}
